In [76]:
import pandas as pd

data = pd.read_csv('../data/registrations.csv')
data.head()

,studentid,semester,grade,major,concentration,code,section,coursetitle,sectiontitle,professor,course-sectiontitle,code-semester,Unnamed: 0,coursetype
0,30876146,0708FA,SR,Engineering,Computing,AHS CAP SPR,1,AHS CapstoneSpring Pre-registration,NaN,"Lynch, Caitrin",AHS CapstoneSpring Pre-registration,AHS CAP SPR 0708FA,247,NaN
1,23925034,0607FA,SR,Engineering,Bioengineering,AHS CAP SPR,1,AHS CapstoneSpring Pre-registration,NaN,"Martello, Robert",AHS CapstoneSpring Pre-registration,AHS CAP SPR 0607FA,247,NaN
2,99052948,0607FA,SR,Electr'l & Computer Engr,NaN,AHS CAP SPR,1,AHS CapstoneSpring Pre-registration,NaN,"Martello, Robert",AHS CapstoneSpring Pre-registration,AHS CAP SPR 0607FA,247,NaN
3,29826367,0607FA,SR,Mechanical Engineering,NaN,AHS CAP SPR,1,AHS CapstoneSpring Pre-registration,NaN,"Martello, Robert",AHS CapstoneSpring Pre-registration,AHS CAP SPR 0607FA,247,NaN
4,91614816,0607FA,SR,Mechanical Engineering,NaN,AHS CAP SPR,1,AHS CapstoneSpring Pre-registration,NaN,"Martello, Robert",AHS CapstoneSpring Pre-registration,AHS CAP SPR 0607FA,247,NaN

In [2]:
data.grade.unique()

array(['SR', 'FR', 'SO', 'JR', 'SP', 'GR', 'XR'], dtype=object)

In [13]:
gds = data.groupby('grade')
for gd in gds:
    print gd[0]
    print len(gd[1])

FR
12283
GR
2
JR
6551
SO
9350
SP
16
SR
6529
XR
1

In [77]:
import string

course_names = data['code'].unique()
course_names = [string.strip(course_name) for course_name in course_names]
df = pd.DataFrame(columns=course_names)
df.head()

Empty DataFrame
Columns: [AHS CAP SPR, AHS1101, AHS1102, AHS1105, AHS1110, AHS1111, AHS1120, AHS1122, AHS1130, AHS1140, AHS1150, AHS2110, AHSE0112, AHSE1100, AHSE1101, AHSE1102, AHSE1122, AHSE1130, AHSE1135, AHSE1140, AHSE1145, AHSE1150, AHSE1155, AHSE1199, AHSE11BA, AHSE1500, AHSE1515, AHSE1599, AHSE2110, AHSE2112, AHSE2114, AHSE2120, AHSE2130, AHSE2131, AHSE2140, AHSE2141, AHSE2170, AHSE2199, AHSE2199A, AHSE2199B, AHSE2199C, AHSE2199E, AHSE2199F, AHSE3100, AHSE3130, AHSE3190, AHSE3199, AHSE3199A, AHSE3500, AHSE3510, AHSE3599, AHSE4190, AHSE4198, AHSE4199, AHSE4590, AHSE4598, AWAY1000, BAB1001, BAB5001, CD1097, CIE2016A, E! CAP SPR, ECE2910, ELE1010, ELE1020, ELE1025, ELE1050, ELE1090, ELE2710, ELE2715, ENG1510, ENGR0097, ENGR0098, ENGR0098X, ENGR1097, ENGR1110, ENGR1120, ENGR1121, ENGR1125, ENGR1199, ENGR1199A, ENGR1200, ENGR1330, ENGR1510, ENGR2141, ENGR2199, ENGR2199A, ENGR2199B, ENGR2199C, ENGR2210, ENGR2250, ENGR2299, ENGR2320, ENGR2330, ENGR2340, ENGR2350, ENGR2410, ENGR2420, ENGR2420 L, ENGR2510, ...]
Index: []

[0 rows x 306 columns]

In [65]:
for gd in gds:
    if gd[0] == 'FR':
        fr = gd[1]
    elif gd[0] == 'SO':
        so = gd[1]
    elif gd[0] == 'JR':
        jr = gd[1]
    elif gd[0] == 'SR':
        sr = gd[1]
    so = so.append(fr)
    jr = jr.append(so)
    sr = sr.append(jr)

In [78]:
grouped = data.groupby('studentid')
for group in grouped:
    student_id = group[0]
    registrations = group[1]
    names = registrations['code'].unique()
    names = [string.strip(name) for name in names]
    df.loc[student_id] = False
    df.loc[student_id, names] = True
    
df['studentid'] = df.index

In [74]:
df.head()

,AHS CAP SPR,AHS1101,AHS1102,AHS1105,AHS1110,AHS1111,AHS1120,AHS1122,AHS1130,AHS1140,...,SEM 302,SEM 303,SEM 401,SEM 402,SEM 501,SEM 502,SEM 503,SUST2201,SUST3301,studentid
10136845,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,10136845
10191843,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,10191843
10208842,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,10208842
10324389,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,10324389
10463379,False,True,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,10463379

In [79]:
df.to_csv('../data/all_enrollment.csv', index=False)